import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { formatter } from '@lingui/format-po';
import { gameMessages } from '../src/i18n/gameMessages';

const sourcePath = resolve('locales/game-messages.ts');
const catalogPath = resolve('src/locales/en/messages.po');

function generatedSource(): string {
  const lines = [
    "import { defineMessage } from '@lingui/core/macro';",
    '',
    '// Generated by scripts/i18n-game.ts. Edit src/i18n/gameMessages.ts instead.',
  ];
  for (const [name, descriptor] of Object.entries(gameMessages)) {
    lines.push(
      `export const ${name} = defineMessage({ id: ${JSON.stringify(descriptor.id)}, message: ${JSON.stringify(descriptor.message)} });`,
    );
  }
  return `${lines.join('\n')}\n`;
}

if (process.argv.includes('--source')) {
  const expected = generatedSource();
  if (process.argv.includes('--check')) {
    const actual = readFileSync(sourcePath, 'utf8');
    if (actual !== expected) throw new Error('locales/game-messages.ts is stale; run npm run i18n:extract');
  } else {
    writeFileSync(sourcePath, expected);
  }
}

if (process.argv.includes('--catalog')) {
  const po = formatter({ lineNumbers: false });
  const existing = readFileSync(catalogPath, 'utf8');
  const catalog = await po.parse(existing, {
    locale: 'en',
    sourceLocale: 'ru',
    filename: 'src/locales/en/messages.po',
  });
  for (const descriptor of Object.values(gameMessages)) {
    const extracted = catalog[descriptor.id];
    if (extracted === undefined) throw new Error(`Lingui did not extract ${descriptor.id}`);
    extracted.translation = descriptor.translation;
  }
  const serialized = await po.serialize(catalog, {
    locale: 'en',
    sourceLocale: 'ru',
    filename: 'src/locales/en/messages.po',
    existing,
  });
  writeFileSync(catalogPath, serialized);
}
