import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { formatter } from '@lingui/format-po';
import { gameMessages } from '../src/i18n/gameMessages';

const sourcePath = resolve('locales/game-messages.ts');
const catalogPath = resolve('src/locales/en/messages.po');

function decodeString(raw: string): string {
  const quote = raw[0];
  let result = '';
  for (let index = 1; index < raw.length - 1; index++) {
    const char = raw[index];
    if (char !== '\\') {
      result += char;
      continue;
    }
    const escaped = raw[++index];
    const simple: Record<string, string> = { n: '\n', r: '\r', t: '\t', b: '\b', f: '\f', v: '\v', '0': '\0' };
    if (escaped in simple) result += simple[escaped];
    else if (escaped === 'x') {
      result += String.fromCodePoint(Number.parseInt(raw.slice(index + 1, index + 3), 16));
      index += 2;
    } else if (escaped === 'u') {
      const braced = raw[index + 1] === '{';
      const end = braced ? raw.indexOf('}', index + 2) : index + 5;
      const digits = raw.slice(index + (braced ? 2 : 1), end);
      result += String.fromCodePoint(Number.parseInt(digits, 16));
      index = end;
    } else result += escaped === quote ? quote : escaped;
  }
  return result;
}

function inlineMessages(): Map<string, string | undefined> {
  const found = new Map<string, string | undefined>();
  const files = readdirSync(resolve('src'), { recursive: true, encoding: 'utf8' })
    .filter((path) => path.endsWith('.ts'));
  const literal = `("(?:\\\\.|[^"\\\\])*"|'(?:\\\\.|[^'\\\\])*')`;
  const call = new RegExp(`\\bgameMessage\\s*\\(\\s*${literal}(?:\\s*,\\s*${literal})?\\s*,?\\s*\\)`, 'g');
  for (const file of files) {
    const source = readFileSync(resolve('src', file), 'utf8');
    for (const match of source.matchAll(call)) {
      const id = decodeString(match[1]);
      const translation = match[2] === undefined ? undefined : decodeString(match[2]);
      const previous = found.get(id);
      if (previous !== undefined && translation !== undefined && previous !== translation) {
        throw new Error(`conflicting inline translations for ${JSON.stringify(id)}`);
      }
      found.set(id, translation ?? previous);
    }
  }
  return new Map([...found].sort(([a], [b]) => a.localeCompare(b, 'ru')));
}

function generatedSource(): string {
  const lines = [
    "import { defineMessage } from '@lingui/core/macro';",
    '',
  '// Generated by scripts/i18n-game.ts. Edit gameMessage() calls or src/i18n/gameMessages.ts instead.',
  ];
  for (const [name, descriptor] of Object.entries(gameMessages)) {
    lines.push(
      `export const ${name} = defineMessage({ id: ${JSON.stringify(descriptor.id)}, message: ${JSON.stringify(descriptor.message)} });`,
    );
  }
  const semanticIds = new Set(Object.values(gameMessages).map(({ id }) => id));
  [...inlineMessages().keys()].filter((source) => !semanticIds.has(source)).forEach((source, index) => {
    lines.push(
      `export const inlineGameMessage${String(index).padStart(4, '0')} = defineMessage({ id: ${JSON.stringify(source)}, message: ${JSON.stringify(source)} });`,
    );
  });
  return `${lines.join('\n')}\n`;
}

if (process.argv.includes('--source')) {
  const expected = generatedSource();
  if (process.argv.includes('--check')) {
    const actual = readFileSync(sourcePath, 'utf8');
    if (actual !== expected) throw new Error('locales/game-messages.ts is stale; run npm run i18n:extract');
  } else {
    writeFileSync(sourcePath, expected);
  }
}

if (process.argv.includes('--catalog')) {
  const po = formatter({ lineNumbers: false });
  const existing = readFileSync(catalogPath, 'utf8');
  const catalog = await po.parse(existing, {
    locale: 'en',
    sourceLocale: 'ru',
    filename: 'src/locales/en/messages.po',
  });
  for (const descriptor of Object.values(gameMessages)) {
    const extracted = catalog[descriptor.id];
    if (extracted === undefined) throw new Error(`Lingui did not extract ${descriptor.id}`);
    if (descriptor.translation !== undefined) extracted.translation = descriptor.translation;
  }
  for (const [source, translation] of inlineMessages()) {
    if (translation === undefined) continue;
    const extracted = catalog[source];
    if (extracted === undefined) throw new Error(`Lingui did not extract ${source}`);
    extracted.translation = translation;
  }
  const serialized = await po.serialize(catalog, {
    locale: 'en',
    sourceLocale: 'ru',
    filename: 'src/locales/en/messages.po',
    existing,
  });
  writeFileSync(catalogPath, serialized);
}
