-- No-op compatibility marker.
--
-- This migration was originally committed with a local timestamp after the
-- equivalent migration had already been applied to the linked project as
-- 20260824122355_player_language.sql. Keeping this version as an explicit
-- no-op aligns migration histories without creating player_settings twice.
